--------------------------------------------------------
--  File created - Sunday-January-15-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CHILD
--------------------------------------------------------

  CREATE TABLE "GSMUSER"."CHILD" 
   (	"CHILDID" NUMBER, 
	"CHILDNAME" VARCHAR2(20 BYTE), 
	"DOB" DATE, 
	"SEX" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PARENT
--------------------------------------------------------

  CREATE TABLE "GSMUSER"."PARENT" 
   (	"PARENTID" NUMBER, 
	"PARENTNAME" VARCHAR2(20 BYTE), 
	"PHONENUMBER" NUMBER, 
	"MAILID" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(50 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"PINCODE" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CHILDPARENTDETAILS
--------------------------------------------------------

  CREATE TABLE "GSMUSER"."CHILDPARENTDETAILS" 
   (	"CHILDID" NUMBER, 
	"PARENTID" NUMBER, 
	"RELATIONSHIP" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VACCINEMASTER
--------------------------------------------------------

  CREATE TABLE "GSMUSER"."VACCINEMASTER" 
   (	"VACCINEID" NUMBER, 
	"DISEASENAME" VARCHAR2(20 BYTE), 
	"VACCINENAME" VARCHAR2(20 BYTE), 
	"PRICE" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DOCTORMASTER
--------------------------------------------------------

  CREATE TABLE "GSMUSER"."DOCTORMASTER" 
   (	"DOCTORID" NUMBER, 
	"DOCTORNAM" VARCHAR2(20 BYTE), 
	"DOCTORPHONENUMBER" NUMBER, 
	"DOCTORMAILID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CLINICMASTER
--------------------------------------------------------

  CREATE TABLE "GSMUSER"."CLINICMASTER" 
   (	"CLINICID" NUMBER, 
	"CLINICNAME" VARCHAR2(20 BYTE), 
	"CLINICPHONENUMBER" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(20 BYTE), 
	"CLINICPINCODE" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CHILDHEALTHREPORT
--------------------------------------------------------

  CREATE TABLE "GSMUSER"."CHILDHEALTHREPORT" 
   (	"RECORDID" NUMBER, 
	"CHILDID" NUMBER, 
	"DATEOFVISIT" DATE, 
	"PURPOSEOFVISIT" VARCHAR2(20 BYTE), 
	"WEIGHT" NUMBER, 
	"HEIGHT" NUMBER, 
	"DOCTORID" NUMBER, 
	"CLINICID" NUMBER, 
	"VACCINEID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CHILD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GSMUSER"."CHILD_PK" ON "GSMUSER"."CHILD" ("CHILDID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PARENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GSMUSER"."PARENT_PK" ON "GSMUSER"."PARENT" ("PARENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CHILDPARENTDETAILS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GSMUSER"."CHILDPARENTDETAILS_PK" ON "GSMUSER"."CHILDPARENTDETAILS" ("CHILDID", "PARENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VACCINEMASTER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GSMUSER"."VACCINEMASTER_PK" ON "GSMUSER"."VACCINEMASTER" ("VACCINEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DOCTORMASTER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GSMUSER"."DOCTORMASTER_PK" ON "GSMUSER"."DOCTORMASTER" ("DOCTORID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CLINICMASTER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GSMUSER"."CLINICMASTER_PK" ON "GSMUSER"."CLINICMASTER" ("CLINICID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GSMUSER"."TABLE1_PK" ON "GSMUSER"."CHILDHEALTHREPORT" ("RECORDID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CHILD
--------------------------------------------------------

  ALTER TABLE "GSMUSER"."CHILD" MODIFY ("CHILDID" NOT NULL ENABLE);
  ALTER TABLE "GSMUSER"."CHILD" MODIFY ("DOB" NOT NULL ENABLE);
  ALTER TABLE "GSMUSER"."CHILD" MODIFY ("SEX" NOT NULL ENABLE);
  ALTER TABLE "GSMUSER"."CHILD" ADD CONSTRAINT "CHILD_PK" PRIMARY KEY ("CHILDID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PARENT
--------------------------------------------------------

  ALTER TABLE "GSMUSER"."PARENT" MODIFY ("PARENTID" NOT NULL ENABLE);
  ALTER TABLE "GSMUSER"."PARENT" MODIFY ("PARENTNAME" NOT NULL ENABLE);
  ALTER TABLE "GSMUSER"."PARENT" MODIFY ("PHONENUMBER" NOT NULL ENABLE);
  ALTER TABLE "GSMUSER"."PARENT" MODIFY ("MAILID" NOT NULL ENABLE);
  ALTER TABLE "GSMUSER"."PARENT" MODIFY ("PINCODE" NOT NULL ENABLE);
  ALTER TABLE "GSMUSER"."PARENT" ADD CONSTRAINT "PARENT_PK" PRIMARY KEY ("PARENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CHILDPARENTDETAILS
--------------------------------------------------------

  ALTER TABLE "GSMUSER"."CHILDPARENTDETAILS" MODIFY ("CHILDID" NOT NULL ENABLE);
  ALTER TABLE "GSMUSER"."CHILDPARENTDETAILS" MODIFY ("PARENTID" NOT NULL ENABLE);
  ALTER TABLE "GSMUSER"."CHILDPARENTDETAILS" ADD CONSTRAINT "CHILDPARENTDETAILS_PK" PRIMARY KEY ("CHILDID", "PARENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VACCINEMASTER
--------------------------------------------------------

  ALTER TABLE "GSMUSER"."VACCINEMASTER" MODIFY ("VACCINEID" NOT NULL ENABLE);
  ALTER TABLE "GSMUSER"."VACCINEMASTER" ADD CONSTRAINT "VACCINEMASTER_PK" PRIMARY KEY ("VACCINEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DOCTORMASTER
--------------------------------------------------------

  ALTER TABLE "GSMUSER"."DOCTORMASTER" MODIFY ("DOCTORID" NOT NULL ENABLE);
  ALTER TABLE "GSMUSER"."DOCTORMASTER" ADD CONSTRAINT "DOCTORMASTER_PK" PRIMARY KEY ("DOCTORID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLINICMASTER
--------------------------------------------------------

  ALTER TABLE "GSMUSER"."CLINICMASTER" MODIFY ("CLINICID" NOT NULL ENABLE);
  ALTER TABLE "GSMUSER"."CLINICMASTER" ADD CONSTRAINT "CLINICMASTER_PK" PRIMARY KEY ("CLINICID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CHILDHEALTHREPORT
--------------------------------------------------------

  ALTER TABLE "GSMUSER"."CHILDHEALTHREPORT" MODIFY ("RECORDID" NOT NULL ENABLE);
  ALTER TABLE "GSMUSER"."CHILDHEALTHREPORT" MODIFY ("CHILDID" NOT NULL ENABLE);
  ALTER TABLE "GSMUSER"."CHILDHEALTHREPORT" MODIFY ("DATEOFVISIT" NOT NULL ENABLE);
  ALTER TABLE "GSMUSER"."CHILDHEALTHREPORT" MODIFY ("DOCTORID" NOT NULL ENABLE);
  ALTER TABLE "GSMUSER"."CHILDHEALTHREPORT" MODIFY ("CLINICID" NOT NULL ENABLE);
  ALTER TABLE "GSMUSER"."CHILDHEALTHREPORT" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("RECORDID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CHILDPARENTDETAILS
--------------------------------------------------------

  ALTER TABLE "GSMUSER"."CHILDPARENTDETAILS" ADD CONSTRAINT "CHILDPARENTDETAILS_FK1" FOREIGN KEY ("CHILDID")
	  REFERENCES "GSMUSER"."CHILD" ("CHILDID") ENABLE;
  ALTER TABLE "GSMUSER"."CHILDPARENTDETAILS" ADD CONSTRAINT "CHILDPARENTDETAILS_FK2" FOREIGN KEY ("PARENTID")
	  REFERENCES "GSMUSER"."PARENT" ("PARENTID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CHILDHEALTHREPORT
--------------------------------------------------------

  ALTER TABLE "GSMUSER"."CHILDHEALTHREPORT" ADD CONSTRAINT "CHILDHEALTHREPORT_FK1" FOREIGN KEY ("CHILDID")
	  REFERENCES "GSMUSER"."CHILD" ("CHILDID") ENABLE;
  ALTER TABLE "GSMUSER"."CHILDHEALTHREPORT" ADD CONSTRAINT "CHILDHEALTHREPORT_FK2" FOREIGN KEY ("DOCTORID")
	  REFERENCES "GSMUSER"."DOCTORMASTER" ("DOCTORID") ENABLE;
  ALTER TABLE "GSMUSER"."CHILDHEALTHREPORT" ADD CONSTRAINT "CHILDHEALTHREPORT_FK3" FOREIGN KEY ("VACCINEID")
	  REFERENCES "GSMUSER"."VACCINEMASTER" ("VACCINEID") ENABLE;
  ALTER TABLE "GSMUSER"."CHILDHEALTHREPORT" ADD CONSTRAINT "CHILDHEALTHREPORT_FK4" FOREIGN KEY ("CLINICID")
	  REFERENCES "GSMUSER"."CLINICMASTER" ("CLINICID") ENABLE;
